package Java;


import Java.AddCompany;
import java.awt.Color;
import Project.JConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL H RAJ
 */
public class AddMedicine extends javax.swing.JFrame {

    /**
     * Creates new form AddMedicine
     */
    
    
    Color blue, white, black, grey;
    public AddMedicine() {
        initComponents();
        blue= new Color(0,118,225);
        white= new Color(255,255,255);
        black= new Color(0,0,0);
        grey= new Color(153,153,153);
        jB1.setBackground(blue);
        jB1.setForeground(white);
        jB2.setBackground(blue);
        jB2.setForeground(white);
        jB3.setBackground(white);
        jB3.setForeground(black);
        jB4.setBackground(blue);
        jB4.setForeground(white);
        jB5.setBackground(blue);
        jB5.setForeground(white);
        jB6.setBackground(blue);
        jB6.setForeground(white);
    }
    
    public void addMedData(){
        int mId= Integer.parseInt(idl1.getText());
        String mName= Tf1.getText();
        int cId= Integer.parseInt(jcid.getText());
        int price= Integer.parseInt(Tf3.getText());
        int quantity= Integer.parseInt(Tf4.getText());
        String validity, status;
        
        java.util.Date mfgDate= rsD1.getDatoFecha();
        java.util.Date expDate= rsD2.getDatoFecha();
        java.sql.Date sMfgD= new java.sql.Date(mfgDate.getTime());
        java.sql.Date sExpD= new java.sql.Date(expDate.getTime());
        Date today= new Date();
        
        String mfg_Date= date2str(sMfgD);
        String exp_Date= date2str(sExpD);
        String td= date2str(today);
        
        int ex= Integer.parseInt(exp_Date);
        int t= Integer.parseInt(td);
        if( ex > t ){
            validity="valid";
            status="active";
        } else{
            validity="expired";
            status="inactive";
        }
        
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("insert into medicine values("+mId+",'"+mName+"',"+cId+","+mfg_Date+","+exp_Date+","+price+","+quantity+",'"+validity+"','"+status+"')");
            JOptionPane.showMessageDialog(null,"Successfully Added!");
            new AddMedicine().setVisible(true);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public String date2str(java.util.Date sdate){
        SimpleDateFormat sdf= new SimpleDateFormat("yyyyMMdd");
        return sdf.format(sdate);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idl1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tf1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rsD1 = new rojeru_san.componentes.RSDateChooser();
        rsD2 = new rojeru_san.componentes.RSDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tf4 = new javax.swing.JTextField();
        rsB = new rojerusan.RSMaterialButtonCircle();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Tf2 = new javax.swing.JTextField();
        idl2 = new javax.swing.JLabel();
        jcid = new javax.swing.JTextField();
        jcb = new javax.swing.JButton();
        BGimage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLable1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 34)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addMedic_48px.png"))); // NOI18N
        jLabel1.setText(" Add Medicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medicine ID   :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 173, -1));

        idl1.setBackground(new java.awt.Color(255, 255, 255));
        idl1.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        idl1.setForeground(new java.awt.Color(153, 255, 0));
        idl1.setText("1000");
        jPanel2.add(idl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 28, 110, 50));

        jLabel7.setBackground(new java.awt.Color(102, 204, 255));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Medicine Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, -1));

        Tf1.setFont(new java.awt.Font("STXinwei", 1, 19)); // NOI18N
        Tf1.setForeground(new java.awt.Color(153, 153, 153));
        Tf1.setText("Enter Medicine Name...");
        Tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tf1FocusLost(evt);
            }
        });
        Tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf1ActionPerformed(evt);
            }
        });
        jPanel2.add(Tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 320, 37));

        jLabel9.setBackground(new java.awt.Color(102, 204, 255));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manufature Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, -1));

        rsD1.setColorBackground(new java.awt.Color(0, 255, 51));
        rsD1.setColorForeground(new java.awt.Color(0, 0, 0));
        rsD1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rsD1.setFuente(new java.awt.Font("STXihei", 1, 17)); // NOI18N
        rsD1.setPlaceholder("Enter Manufacture Date");
        jPanel2.add(rsD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 320, 40));

        rsD2.setColorBackground(new java.awt.Color(0, 255, 51));
        rsD2.setColorForeground(new java.awt.Color(0, 0, 0));
        rsD2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rsD2.setFuente(new java.awt.Font("STXihei", 1, 17)); // NOI18N
        rsD2.setPlaceholder("Enter Expiry Date");
        jPanel2.add(rsD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 320, -1));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Expiry Date");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 430, 560));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tf3.setFont(new java.awt.Font("STXinwei", 1, 19)); // NOI18N
        Tf3.setForeground(new java.awt.Color(153, 153, 153));
        Tf3.setText("Enter the price...");
        Tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tf3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tf3FocusLost(evt);
            }
        });
        jPanel3.add(Tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 35));

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price per unit");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, -1));

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, -1));

        Tf4.setFont(new java.awt.Font("STXinwei", 1, 19)); // NOI18N
        Tf4.setForeground(new java.awt.Color(153, 153, 153));
        Tf4.setText("Enter the no. of Units...");
        Tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tf4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tf4FocusLost(evt);
            }
        });
        jPanel3.add(Tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 300, 35));

        rsB.setBackground(new java.awt.Color(255, 255, 255));
        rsB.setForeground(new java.awt.Color(0, 102, 51));
        rsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        rsB.setText("Save & Add");
        rsB.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        rsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsBActionPerformed(evt);
            }
        });
        jPanel3.add(rsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 216, 50));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 418, 10));

        jLabel6.setBackground(new java.awt.Color(102, 204, 255));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        Tf2.setFont(new java.awt.Font("STXinwei", 1, 19)); // NOI18N
        Tf2.setForeground(new java.awt.Color(153, 153, 153));
        Tf2.setText("Enter Company Name...");
        Tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tf2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tf2FocusLost(evt);
            }
        });
        jPanel3.add(Tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 320, 35));

        idl2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        idl2.setForeground(new java.awt.Color(255, 255, 255));
        idl2.setText("Company ID:");
        jPanel3.add(idl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 30));

        jcid.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jcid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcid.setToolTipText("");
        jcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcidActionPerformed(evt);
            }
        });
        jPanel3.add(jcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, -1));

        jcb.setBackground(new java.awt.Color(102, 255, 0));
        jcb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sync_64px_1_24x24.png"))); // NOI18N
        jcb.setText("Get ID");
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });
        jPanel3.add(jcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 124, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 430, 560));

        BGimage.setForeground(new java.awt.Color(255, 51, 51));
        BGimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Meds.jpg"))); // NOI18N
        BGimage.setText("jLabel8");
        jPanel1.add(BGimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1096, 660));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close_.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 50, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1096, 768));

        jPanel5.setBackground(new java.awt.Color(0, 118, 225));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLable1.setBackground(new java.awt.Color(64, 64, 64));
        jLable1.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLable1.setForeground(new java.awt.Color(242, 242, 242));
        jLable1.setText("  Administrator");
        jPanel5.add(jLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 166, 44));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin3_1_100x100.png"))); // NOI18N
        jLabel10.setText("jLabel3");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 120));

        jB1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashbord.png"))); // NOI18N
        jB1.setText("Dashboard");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel5.add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 40));

        jB2.setBackground(new java.awt.Color(0, 118, 225));
        jB2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB2.setForeground(new java.awt.Color(255, 255, 255));
        jB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_25px.png"))); // NOI18N
        jB2.setText(" Customer");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel5.add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 250, 40));

        jB3.setBackground(new java.awt.Color(0, 118, 225));
        jB3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB3.setForeground(new java.awt.Color(255, 255, 255));
        jB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addMedic_48px_32x32.png"))); // NOI18N
        jB3.setText("Add Medicine");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel5.add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, 40));

        jB4.setBackground(new java.awt.Color(0, 118, 225));
        jB4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB4.setForeground(new java.awt.Color(255, 255, 255));
        jB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyMedicine_32px.png"))); // NOI18N
        jB4.setText("Update Medicine");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel5.add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 40));

        jB5.setBackground(new java.awt.Color(0, 118, 225));
        jB5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB5.setForeground(new java.awt.Color(255, 255, 255));
        jB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view_64px_32x32.png"))); // NOI18N
        jB5.setText("View Medicines");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        jPanel5.add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 250, 40));

        jB6.setBackground(new java.awt.Color(0, 118, 225));
        jB6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB6.setForeground(new java.awt.Color(255, 255, 255));
        jB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sellMedicine_64px_32x32.png"))); // NOI18N
        jB6.setText("Sell Medicine");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        jPanel5.add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 250, 40));

        jB7.setBackground(new java.awt.Color(0, 118, 225));
        jB7.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        jB7.setForeground(new java.awt.Color(255, 255, 255));
        jB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_32x32.png"))); // NOI18N
        jB7.setText("Logout");
        jB7.setBorder(null);
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jPanel5.add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 210, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf1FocusGained
        // TODO add your handling code here:
        if(Tf1.getText().equals("Enter Medicine Name..."))
        {
            Tf1.setText("");
            Tf1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Tf1FocusGained

    private void Tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf1FocusLost
        // TODO add your handling code here:
        if(Tf1.getText().equals(""))
        {
            Tf1.setText("Enter Medicine Name...");
            Tf1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Tf1FocusLost

    private void Tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf1ActionPerformed
        // TODO add your handling code here:
        String mName= Tf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from medicine where medName='"+mName+"'");
            if(rs.next()){
                int a= JOptionPane.showConfirmDialog(null,"This medcine name already exists!\nDo you want to update the details of it?","Message!",JOptionPane.YES_NO_OPTION);
                if(a==0){
                    UpdateMedicine um= new UpdateMedicine();
                    um.searchMed(mName);
                    um.setVisible(true);
                }
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_Tf1ActionPerformed

    private void Tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf2FocusGained
        // TODO add your handling code here:
        if(Tf2.getText().equals("Enter Company Name..."))
        {
            Tf2.setText("");
            Tf2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Tf2FocusGained

    private void Tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf2FocusLost
        // TODO add your handling code here:
        if(Tf2.getText().equals(""))
        {
            Tf2.setText("Enter Company Name...");
            Tf2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Tf2FocusLost

    private void Tf3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf3FocusGained
        // TODO add your handling code here:
        if(Tf3.getText().equals("Enter the price..."))
        {
            Tf3.setText("");
            Tf3.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Tf3FocusGained

    private void Tf3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf3FocusLost
        // TODO add your handling code here:
        if(Tf3.getText().equals(""))
        {
            Tf3.setText("Enter the price...");
            Tf3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Tf3FocusLost

    private void rsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsBActionPerformed
        // TODO add your handling code here:
        try{
            int q= Integer.parseInt(Tf4.getText());
            int price= Integer.parseInt(Tf3.getText());
            java.util.Date mfgDate= rsD1.getDatoFecha();
            java.util.Date expDate= rsD2.getDatoFecha();
            Date today= new Date();
            String md= date2str(mfgDate);
            String ed= date2str(expDate);
            String td= date2str(today);
            int m= Integer.parseInt(md);
            int e= Integer.parseInt(ed);
            int t= Integer.parseInt(td);
            if((q > 100)){
                JOptionPane.showMessageDialog(null,"Entered Quantity exceeds the LIMIT!","INVALID!",JOptionPane.ERROR_MESSAGE);
                Tf4.setText("");
            }
            else if((q < 1)){
                JOptionPane.showMessageDialog(null,"No. of Medicine Units cannot be Negative!","INVALID!",JOptionPane.ERROR_MESSAGE);
                Tf4.setText("");
            }
            else if(price <= 0){
                JOptionPane.showMessageDialog(null,"Price cannot be Negative!","INVALID!",JOptionPane.ERROR_MESSAGE);
                Tf3.setText("");
            }
            else if((mfgDate.compareTo(expDate)>=0)||(m >= t)){
                JOptionPane.showMessageDialog(null,"Please Enter the Valid Date for the 'Manufacture Date'!","INVALID!",JOptionPane.ERROR_MESSAGE);
            } 
            else if(((e-m) <= 230)||((e-m) >= 10000)){
                JOptionPane.showMessageDialog(null,"Please Enter the Valid Date for the 'Expiry Date'!","INVALID!",JOptionPane.ERROR_MESSAGE);
            } 
            else{
                addMedData();    
            }
        } catch(Exception e){}
    }//GEN-LAST:event_rsBActionPerformed

    private void Tf4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf4FocusGained
        // TODO add your handling code here:
        if(Tf4.getText().equals("Enter the no. of Units..."))
        {
            Tf4.setText("");
            Tf4.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Tf4FocusGained

    private void Tf4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf4FocusLost
        // TODO add your handling code here:
        if(Tf4.getText().equals(""))
        {
            Tf4.setText("Enter the no. of Units...");
            Tf4.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Tf4FocusLost

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        // TODO add your handling code here:
        String cName= Tf2.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from company where compName like '"+cName+"%'");
            if(rs.next()){
                Tf2.setForeground(black);
                Tf2.setText(rs.getString(2));
                jcid.setText(rs.getString(1));
            } else{
                int a= JOptionPane.showConfirmDialog(null,"Entered Company's data NOT FOUND!\nDo you want to add New Company' details?","Message",JOptionPane.YES_NO_OPTION);
                if(a==0){
                    new AddCompany().setVisible(true);
                }    
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_jcbActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select max(medId) from medicine");
            if(rs.next()){
                int id= rs.getInt(1);
                id = id + 1;
                String str= String.valueOf(id);
                idl1.setText(str);
            } else{
                idl1.setText("1000");
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_formComponentShown

    private void jcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcidActionPerformed
        // TODO add your handling code here:
        String id= jcid.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select compName from company where compId="+id);
            if(rs.next()){
                Tf2.setForeground(black);
                Tf2.setText(rs.getString(1));
            } else{
                JOptionPane.showMessageDialog(null,"Entered Company_ID doesn't Exist!");
                Tf2.setText("");
                jcid.setText("");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_jcidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] options= {"Dashboard","Exit Application"};
        int a= JOptionPane.showOptionDialog(null,"Your Choice","Select",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,null);
        if(a == 0){
            new Home().setVisible(true);
            dispose();
        } else if(a == 1){
            int b= JOptionPane.showConfirmDialog(null,"Do you really want to exit the Application?","Confirm!",JOptionPane.YES_NO_OPTION);
            if(b == 0){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        new AddMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        new UpdateMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        new ViewMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        new SellMedicine().setVisible(true);
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        int a= JOptionPane.showConfirmDialog(null,"Do you really want to Logout?","Confirm!",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jB7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimage;
    private javax.swing.JTextField Tf1;
    private javax.swing.JTextField Tf2;
    private javax.swing.JTextField Tf3;
    private javax.swing.JTextField Tf4;
    private javax.swing.JLabel idl1;
    private javax.swing.JLabel idl2;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jcb;
    private javax.swing.JTextField jcid;
    private rojerusan.RSMaterialButtonCircle rsB;
    private rojeru_san.componentes.RSDateChooser rsD1;
    private rojeru_san.componentes.RSDateChooser rsD2;
    // End of variables declaration//GEN-END:variables
}
