package Java;


import Project.JConnection;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.*;
import java.awt.Color;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL H RAJ
 */
public class SellMedicine extends javax.swing.JFrame {
    public int actualTotal= 0, bal, rem;

    /**
     * Creates new form SellMedicine
     */
    
    public String dt, tm;
    DefaultTableModel model;
    Color green, white, grey, black;
    public SellMedicine() {
        initComponents();
        
        green= new Color(0,102,51);
        white= new Color(255,255,255);
        grey= new Color(153,153,153);
        black= new Color(0,0,0);
        mf3.setEditable(false);
        mf4.setEditable(false);
        oid.setEditable(false);
        atot.setEditable(false);
        ramt.setEditable(false);
        tot.setEditable(false);
        
        
        SimpleDateFormat df= new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat df1= new SimpleDateFormat("yyyyMMdd");
        Date date= new Date();
        datel.setText(df.format(date));
        dt= df1.format(date);
        
        DateTimeFormatter dtf= DateTimeFormatter.ofPattern("HH:mm:ss");
        DateTimeFormatter dtf1= DateTimeFormatter.ofPattern("HHmmss");
        LocalDateTime now=LocalDateTime.now();
        timel.setText(dtf.format(now));
        tm= dtf1.format(now);
    }
    
    public void add2Orders(){
        String oId= oid.getText();
        String cId= cf1.getText();
        String totamt= atot.getText();
        String oDate= dt+tm;
        updatePurchase();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("insert into bill values("+oId+","+cId+","+totamt+","+oDate+")");
            JOptionPane.showMessageDialog(null,"Order placed Successfully!");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Order has already been placed!\nPlease hit the 'Reset' button for the new Order.");
        }
    }
    
    public boolean deleteQ(int mId, int qty){
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("update medicine set quantity = quantity - "+qty+" where medId="+mId);
            return true;
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }
    
    public void updateQ(int mId, int qty){
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("update medicine set quantity = quantity + "+qty+" where medId="+mId);
        } catch(Exception e){
        }
    }
    
    public void updatePurchase(){
        String cId= cf1.getText();
        String oDate= dt+tm;
        TableModel model= Cart_Table.getModel();
        try{
            for(int i=0; i<model.getRowCount(); i++){
                String mId= model.getValueAt(i, 0).toString();
                String quantity= model.getValueAt(i, 3).toString();
                Connection con= JConnection.getCon();
                Statement st= con.createStatement();
                st.executeUpdate("insert into purchase values("+oDate+","+cId+","+mId+","+quantity+")");
            }
        } catch(Exception e){}
    }
    
    public void addBalance(){
        int b= Integer.parseInt(ramt.getText());
        String id= cf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("update customer set balance = balance + "+b+" where cId="+id);
        } catch(Exception e){
        }
    }
    
    public void updateBalance(){
        String id= cf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("update customer set balance ="+bal+" where cId="+id);
        } catch(Exception e){
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        a2c = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        cf1 = new javax.swing.JTextField();
        cf2 = new javax.swing.JTextField();
        cf3 = new javax.swing.JTextField();
        cf4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        mf1 = new javax.swing.JTextField();
        mf2 = new javax.swing.JTextField();
        mf3 = new javax.swing.JTextField();
        mf4 = new javax.swing.JTextField();
        mf5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        datel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart_Table = new rojeru_san.complementos.RSTableMetro();
        jLabel16 = new javax.swing.JLabel();
        rb = new javax.swing.JButton();
        sb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        atot = new javax.swing.JTextField();
        pamt = new javax.swing.JTextField();
        ramt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        oid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cb = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        rm = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing frame.png"))); // NOI18N
        jLabel1.setText(" Sell Medicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 330, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingIcon.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 136));

        jb1.setBackground(new java.awt.Color(0, 102, 204));
        jb1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setText("Customer Details");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jPanel1.add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, -1));

        jb2.setBackground(new java.awt.Color(0, 102, 0));
        jb2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setText("Medicine Details");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jPanel1.add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 160, -1));

        a2c.setBackground(new java.awt.Color(153, 153, 153));
        a2c.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        a2c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_to_cart_40px.png"))); // NOI18N
        a2c.setText(" Add to Cart");
        a2c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a2cMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                a2cMouseReleased(evt);
            }
        });
        a2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2cActionPerformed(evt);
            }
        });
        jPanel1.add(a2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 400, 170, 60));

        jp1.setBackground(new java.awt.Color(0, 102, 153));
        jp1.setForeground(new java.awt.Color(255, 255, 255));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cf1ActionPerformed(evt);
            }
        });
        jp1.add(cf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 80, -1));

        cf2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cf2ActionPerformed(evt);
            }
        });
        jp1.add(cf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 250, -1));

        cf3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jp1.add(cf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, 140, -1));

        cf4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cf4ActionPerformed(evt);
            }
        });
        jp1.add(cf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID :");
        jp1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name :");
        jp1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 60, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Balance (if any):");
        jp1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact No. :");
        jp1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 110, 30));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jp1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 40, -1, 30));

        jPanel1.add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1330, 100));

        jp2.setBackground(new java.awt.Color(0, 102, 102));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        mf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mf1ActionPerformed(evt);
            }
        });
        jp2.add(mf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 80, -1));

        mf2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        mf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mf2ActionPerformed(evt);
            }
        });
        jp2.add(mf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 250, -1));

        mf3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jp2.add(mf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 160, -1));

        mf4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jp2.add(mf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 120, -1));

        mf5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jp2.add(mf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID :");
        jp2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name :");
        jp2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 60, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Company :");
        jp2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price :");
        jp2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity :");
        jp2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 90, 30));

        jPanel1.add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1330, 110));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1350, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1350, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1350, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Date    :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 70, 20));

        datel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(datel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 130, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Time    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 70, 20));

        timel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(timel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 130, 20));

        Cart_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Med_ID", "Med_Name", "Rate", "Quantity", "Total"
            }
        ));
        Cart_Table.setColorBackgoundHead(new java.awt.Color(255, 255, 102));
        Cart_Table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Cart_Table.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        Cart_Table.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        Cart_Table.setFuenteFilas(new java.awt.Font("Noto Serif", 1, 15)); // NOI18N
        Cart_Table.setFuenteFilasSelect(new java.awt.Font("Noto Serif", 1, 15)); // NOI18N
        Cart_Table.setFuenteHead(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        Cart_Table.setRowHeight(24);
        Cart_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Cart_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cart_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Cart_Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 570, 230));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setText("   Cart Details:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 466, 230, 30));

        rb.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        rb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        rb.setText("Reset");
        rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });
        jPanel1.add(rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 630, 110, -1));

        sb.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        sb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        sb.setText("Save");
        sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbActionPerformed(evt);
            }
        });
        jPanel1.add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, 110, -1));

        jPanel2.setBackground(new java.awt.Color(225, 225, 225));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Actual Total          :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Paid Amount         :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Amount(to Pay)    :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        atot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(atot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 170, 40));

        pamt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pamtActionPerformed(evt);
            }
        });
        jPanel2.add(pamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 40));

        ramt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(ramt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 40));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setText("Order No.             :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, -1));

        oid.setBackground(new java.awt.Color(255, 204, 204));
        oid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oid.setForeground(new java.awt.Color(204, 0, 0));
        oid.setText("1");
        jPanel2.add(oid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 40));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Return Amount    :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 170, -1));

        tot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totActionPerformed(evt);
            }
        });
        jPanel2.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 40));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyMedicine_32px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 480, 260));

        cb.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        cb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        cb.setText("Close");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel1.add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 690, 110, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setText("Calculation Details:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 180, -1));

        rm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove_25px.png"))); // NOI18N
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        jPanel1.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 677, -1, 50));

        ex.setBackground(new java.awt.Color(0, 0, 0));
        ex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no.png"))); // NOI18N
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        jPanel1.add(ex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 50, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setText("Previous Purchase Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 108, 220, 30));

        jButton2.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 570, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a2cMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2cMousePressed
        // TODO add your handling code here:
        a2c.setBackground(green);
        a2c.setForeground(white);
    }//GEN-LAST:event_a2cMousePressed

    private void a2cMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2cMouseReleased
        // TODO add your handling code here:
        a2c.setBackground(grey);
        a2c.setForeground(black);
    }//GEN-LAST:event_a2cMouseReleased

    private void cf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cf1ActionPerformed
        // TODO add your handling code here:
        String cid= cf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from customer where cId ="+cid);
            if(rs.next()){
                cf2.setText(rs.getString(2));
                cf4.setText(rs.getString(3));
                bal= Integer.parseInt(rs.getString(5));
            } else{
                cf1.setText("");
                cf2.setText("");
                cf4.setText("");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_cf1ActionPerformed

    private void rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SellMedicine().setVisible(true);
    }//GEN-LAST:event_rbActionPerformed

    private void sbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbActionPerformed
        // TODO add your handling code here:
        add2Orders();
    }//GEN-LAST:event_sbActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cbActionPerformed

    private void cf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cf2ActionPerformed
        // TODO add your handling code here:
        String cname= cf2.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from customer where name like '"+cname+"%'");
            if(rs.next()){
                cf1.setText(rs.getString(1));
                cf2.setText(rs.getString(2));
                cf4.setText(rs.getString(3));
                bal= Integer.parseInt(rs.getString(5));
            } else{
                cf1.setText("");
                cf2.setText("");
                cf4.setText("");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_cf2ActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewMedicine().setVisible(true);
    }//GEN-LAST:event_exActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select max(orderId) from bill");
            if(rs.next()){
                int id= rs.getInt(1);
                id = id + 1;
                String str= String.valueOf(id);
                oid.setText(str);
            } else{
                oid.setText("1");
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_formComponentShown

    private void cf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cf4ActionPerformed
        // TODO add your handling code here:
        String phno= cf4.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from customer where contactNo like '"+phno+"%'");
            if(rs.next()){
                cf1.setText(rs.getString(1));
                cf2.setText(rs.getString(2));
                cf4.setText(rs.getString(3));
                bal= Integer.parseInt(rs.getString(5));
            } else{
                cf1.setText("");
                cf2.setText("");
                cf4.setText("");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_cf4ActionPerformed

    private void mf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mf1ActionPerformed
        // TODO add your handling code here:
        if(cf1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter the Customer details first!");
            mf1.setText("");
        } else{
        String mid= mf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select medId, medName, compName, price from medicine m, company c where m.compId=c.compId and medId ="+mid+" and status='active'");
            if(rs.next()){
                mf2.setText(rs.getString(2));
                mf3.setText(rs.getString(3));
                mf4.setText(rs.getString(4));
            } else{
                mf1.setText("");
                mf2.setText("");
                mf3.setText("");
                mf4.setText("");
                mf5.setText("");
            }
        } catch(Exception e){}}
    }//GEN-LAST:event_mf1ActionPerformed

    private void mf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mf2ActionPerformed
        // TODO add your handling code here:
        if(cf1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter the Customer details first!");
            mf2.setText("");
        } else{
        String mname= mf2.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select medId, medName, compName, price from medicine m, company c where m.compId=c.compId and medName like '"+mname+"%' and status='active'");
            if(rs.next()){
                mf1.setText(rs.getString(1));
                mf2.setText(rs.getString(2));
                mf3.setText(rs.getString(3));
                mf4.setText(rs.getString(4));
            } else{
                mf1.setText("");
                mf2.setText("");
                mf3.setText("");
                mf4.setText("");
                mf5.setText("");
            }
        } catch(Exception e){}}
    }//GEN-LAST:event_mf2ActionPerformed

    private void a2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2cActionPerformed
        // TODO add your handling code here:
        if ((!"".equals(cf1.getText()))&&(!"".equals(mf1.getText()))){
            int mId= Integer.parseInt(mf1.getText());
            int price= Integer.parseInt(mf4.getText());
            int qty= Integer.parseInt(mf5.getText());
            int tot= price*qty;
            if(deleteQ(mId,qty)){
                model= (DefaultTableModel) Cart_Table.getModel();
                model.addRow(new Object[]{mf1.getText(),mf2.getText(),price,qty,tot});
                JOptionPane.showMessageDialog(null,"Added to the Cart!");
                actualTotal= actualTotal+tot;
                String aT= String.valueOf(actualTotal);
                atot.setText(aT);
                mf1.setText("");
                mf2.setText("");
                mf3.setText("");
                mf4.setText("");
                mf5.setText("");
            }
        }
    }//GEN-LAST:event_a2cActionPerformed

    private void pamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pamtActionPerformed
        // TODO add your handling code here:
        int total= Integer.parseInt(tot.getText());
        int p= Integer.parseInt(pamt.getText());
        int r= p-total;
        if(r < 0){
            JOptionPane.showMessageDialog(null, "Insufficient Amount!");
            pamt.setText("");
        } else{
            ramt.setText(Integer.toString(r));
            updateBalance();
            if(r > 0){
                int a= JOptionPane.showConfirmDialog(null,"Do the customer want to add this extra Amount to his/her Balance?","Confirm!",JOptionPane.YES_NO_OPTION);
                if(a==0){
                    addBalance();
                    ramt.setText("");
                }
            }
        }
    }//GEN-LAST:event_pamtActionPerformed

    private void Cart_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cart_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cart_TableMouseClicked

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
        if(Cart_Table.getSelectedRow() != -1){
        int rowNo= Cart_Table.getSelectedRow();
        model= (DefaultTableModel) Cart_Table.getModel();
        int p= Integer.parseInt(model.getValueAt(rowNo, 4).toString());
        int q= Integer.parseInt(model.getValueAt(rowNo, 3).toString());
        int id= Integer.parseInt(model.getValueAt(rowNo, 0).toString());
        try{
        if(Cart_Table.getSelectedRow()!=1){
            model.removeRow(Cart_Table.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Removed from the Cart!");
            actualTotal= actualTotal - p;
            String aT= String.valueOf(actualTotal);
            atot.setText(aT);
            updateQ(id,q);
        }} catch(Exception e){}}
    }//GEN-LAST:event_rmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new PurchaseDetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name= cf2.getText();
        String phno= cf4.getText();
        String path= "D:\\BILL\\";
        com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+name+" "+datel.getText()+".pdf"));
            doc.open();
            Paragraph para1= new Paragraph("                                            Pharmacy Management System\n\nContactNo: (+91)9480005711, (+91)8277163326\n");
            doc.add(para1);
            Paragraph para2= new Paragraph("Date & Time: "+datel.getText()+"  "+timel.getText()+"\n\nBuyer Details:\nName: "+name+"\nPhoneNo :"+phno+"\n\nMedicine Details:\n\n");
            doc.add(para2);
            
            PdfPTable tb1= new PdfPTable(5);
            tb1.addCell("Sl.No.");
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("SubTotal");
            for(int i=0; i<Cart_Table.getRowCount(); i++){
                String s= Integer.toString(i+1);
                String n= Cart_Table.getValueAt(i, 1).toString();
                String p= Cart_Table.getValueAt(i, 2).toString();
                String q= Cart_Table.getValueAt(i, 3).toString();
                String st= Cart_Table.getValueAt(i, 4).toString();
                tb1.addCell(s);
                tb1.addCell(n);
                tb1.addCell(p);
                tb1.addCell(q);
                tb1.addCell(st);
            }
            doc.add(tb1);
            Paragraph para3= new Paragraph("\nTotal Amount :"+atot.getText()+"\n\nThank You for visiting! Please come Again!\n-RV Admin");
            doc.add(para3);
            doc.close();
            JOptionPane.showMessageDialog(null, "Bill Generated!");            
        } catch(Exception e){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cid= cf1.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select balance from customer where cId ="+cid);
            if(rs.next()){
                bal= Integer.parseInt(rs.getString(1));
            }
            if(bal == 0)
                cf3.setText("No");
            else
                cf3.setText(Integer.toString(bal));
        } catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int total= actualTotal;
        if(bal != 0){
            int a= JOptionPane.showConfirmDialog(null,"Do the customer want to use his/her Balance amount?","Confirm!",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                if((total-bal)>=0){
                    total= total - bal;
                    bal= 0;
                } else{
                    bal= bal - total;
                    total= 0;               
                }
            }
        }
        String t= String.valueOf(total);
        tot.setText(t);        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        // TODO add your handling code here:
        cf1.setText("");
        cf2.setText("");
        cf3.setText("");
        cf4.setText("");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
        mf1.setText("");
        mf2.setText("");
        mf3.setText("");
        mf4.setText("");
        mf5.setText("");
    }//GEN-LAST:event_jb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro Cart_Table;
    private javax.swing.JButton a2c;
    private javax.swing.JTextField atot;
    private javax.swing.JButton cb;
    private javax.swing.JTextField cf1;
    private javax.swing.JTextField cf2;
    private javax.swing.JTextField cf3;
    private javax.swing.JTextField cf4;
    private javax.swing.JLabel datel;
    private javax.swing.JButton ex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JTextField mf1;
    private javax.swing.JTextField mf2;
    private javax.swing.JTextField mf3;
    private javax.swing.JTextField mf4;
    private javax.swing.JTextField mf5;
    private javax.swing.JTextField oid;
    private javax.swing.JTextField pamt;
    private javax.swing.JTextField ramt;
    private javax.swing.JButton rb;
    private javax.swing.JButton rm;
    private javax.swing.JButton sb;
    private javax.swing.JLabel timel;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
