package Java;


import Java.SellMedicine;
import Java.Login;
import Java.Home;
import Java.Customer;
import Java.AddMedicine;
import Project.JConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL H RAJ
 */
public class UpdateMedicine extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMedicine
     */
    
    Color blue, white, black;
    public UpdateMedicine() {
        initComponents();
        blue= new Color(0,118,225);
        white= new Color(255,255,255);
        black= new Color(0,0,0);
        jB1.setBackground(blue);
        jB1.setForeground(white);
        jB2.setBackground(blue);
        jB2.setForeground(white);
        jB3.setBackground(blue);
        jB3.setForeground(white);
        jB4.setBackground(white);
        jB4.setForeground(black);
        jB5.setBackground(blue);
        jB5.setForeground(white);
        jB6.setBackground(blue);
        jB6.setForeground(white);
        Tf2.setEditable(false);
        Tf4.setEditable(false);
    }
    
    public void updateMed(){
        int mId= Integer.parseInt(Stf.getText());
        String mName= Tf1.getText();
        int cId= Integer.parseInt(Tf2.getText());
        int price= Integer.parseInt(Tf3.getText());
        int quantity= Integer.parseInt(Tf4.getText());
        String validity, status;
        
        java.util.Date mfgDate= rsD1.getDatoFecha();
        java.util.Date expDate= rsD2.getDatoFecha();
        java.sql.Date sMfgD= new java.sql.Date(mfgDate.getTime());
        java.sql.Date sExpD= new java.sql.Date(expDate.getTime());
        Date today= new Date();
        
        String mfg_Date= date2str(sMfgD);
        String exp_Date= date2str(sExpD);
        String td= date2str(today);
        
        int ex= Integer.parseInt(exp_Date);
        int t= Integer.parseInt(td);
        if( ex > t ){
            validity="valid";
            status="active";
        } else{
            validity="expired";
            status="inactive";
        }
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("update medicine set medName='"+mName+"', compId="+cId+", mfgDate="+mfg_Date+", expDate="+exp_Date+", price="+price+", quantity="+quantity+", validity='"+validity+"', status='"+status+"' where medId="+mId);
            JOptionPane.showMessageDialog(null,"Successfully Updated!");
        } catch(Exception e){}
    }
    
    public void deleteMed(){
        String id= Stf.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("delete from medicine where medId="+id);
            JOptionPane.showMessageDialog(null,"Deletion Successful!");
        } catch(Exception e){
            
        }
    }
    
    public void searchMed(String name){
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from medicine where medName like '"+name+"%'");
            if(rs.next()){
                Stf.setText(rs.getString(1));
                Tf1.setText(rs.getString(2));
                rsD1.setDatoFecha(rs.getDate(4));
                rsD2.setDatoFecha(rs.getDate(5));
                Tf2.setText(rs.getString(3));
                Tf4.setText(rs.getString(7));
                Tf3.setText(rs.getString(6));
                Stf.setEditable(false);
            }
        } catch(Exception e){
        }
    }
    
    public String date2str(java.util.Date sdate){
        SimpleDateFormat sdf= new SimpleDateFormat("yyyyMMdd");
        return sdf.format(sdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tf1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rsD1 = new rojeru_san.componentes.RSDateChooser();
        rsD2 = new rojeru_san.componentes.RSDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Stf = new javax.swing.JTextField();
        Sb = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tf4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Tf2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        adq = new javax.swing.JTextField();
        Ub = new javax.swing.JButton();
        Db = new javax.swing.JButton();
        BGimage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLable1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        jLabel1.setText("Update Medicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(102, 204, 255));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Medicine Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, -1));

        Tf1.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        Tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf1ActionPerformed(evt);
            }
        });
        jPanel2.add(Tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 320, 35));

        jLabel9.setBackground(new java.awt.Color(102, 204, 255));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manufacture Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, -1));

        rsD1.setColorBackground(new java.awt.Color(0, 255, 51));
        rsD1.setColorForeground(new java.awt.Color(0, 0, 0));
        rsD1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rsD1.setFuente(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        rsD1.setPlaceholder("");
        jPanel2.add(rsD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 320, 40));

        rsD2.setColorBackground(new java.awt.Color(0, 255, 51));
        rsD2.setColorForeground(new java.awt.Color(0, 0, 0));
        rsD2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rsD2.setFuente(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        rsD2.setPlaceholder("");
        jPanel2.add(rsD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 320, -1));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Expiry Date");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, -1));

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID   :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 50));

        Stf.setFont(new java.awt.Font("Noto Serif Light", 1, 18)); // NOI18N
        jPanel2.add(Stf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, -1));

        Sb.setFont(new java.awt.Font("Source Serif Pro Light", 1, 14)); // NOI18N
        Sb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        Sb.setText("Search");
        Sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbActionPerformed(evt);
            }
        });
        jPanel2.add(Sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 430, 560));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tf3.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        jPanel3.add(Tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, -1));

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price per unit");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 130, -1));

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Available Quantity");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, -1));

        Tf4.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        jPanel3.add(Tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 418, 10));

        jLabel6.setBackground(new java.awt.Color(102, 204, 255));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, -1));

        Tf2.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        jPanel3.add(Tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 310, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Quantity :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, 50));

        adq.setBackground(new java.awt.Color(153, 255, 153));
        adq.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jPanel3.add(adq, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, 30));

        Ub.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        Ub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Ub.setText("Update");
        Ub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbActionPerformed(evt);
            }
        });
        jPanel3.add(Ub, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 120, -1));

        Db.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        Db.setForeground(new java.awt.Color(204, 0, 0));
        Db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        Db.setText("Delete");
        Db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbActionPerformed(evt);
            }
        });
        jPanel3.add(Db, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 430, 560));

        BGimage.setForeground(new java.awt.Color(255, 51, 51));
        BGimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Meds.jpg"))); // NOI18N
        BGimage.setText("jLabel8");
        jPanel1.add(BGimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1096, 660));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sync_64px_1_48x48.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close_.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 50, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1096, 768));

        jPanel5.setBackground(new java.awt.Color(0, 118, 225));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLable1.setBackground(new java.awt.Color(64, 64, 64));
        jLable1.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLable1.setForeground(new java.awt.Color(242, 242, 242));
        jLable1.setText("  Administrator");
        jPanel5.add(jLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 166, 44));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin3_1_100x100.png"))); // NOI18N
        jLabel12.setText("jLabel3");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 120));

        jB1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashbord.png"))); // NOI18N
        jB1.setText("Dashboard");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel5.add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 40));

        jB2.setBackground(new java.awt.Color(0, 118, 225));
        jB2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB2.setForeground(new java.awt.Color(255, 255, 255));
        jB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_25px.png"))); // NOI18N
        jB2.setText(" Customer");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel5.add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 250, 40));

        jB3.setBackground(new java.awt.Color(0, 118, 225));
        jB3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB3.setForeground(new java.awt.Color(255, 255, 255));
        jB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addMedic_48px_32x32.png"))); // NOI18N
        jB3.setText("Add Medicine");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel5.add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, 40));

        jB4.setBackground(new java.awt.Color(0, 118, 225));
        jB4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB4.setForeground(new java.awt.Color(255, 255, 255));
        jB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyMedicine_32px.png"))); // NOI18N
        jB4.setText("Update Medicine");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel5.add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 40));

        jB5.setBackground(new java.awt.Color(0, 118, 225));
        jB5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB5.setForeground(new java.awt.Color(255, 255, 255));
        jB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view_64px_32x32.png"))); // NOI18N
        jB5.setText("View Medicines");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        jPanel5.add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 250, 40));

        jB6.setBackground(new java.awt.Color(0, 118, 225));
        jB6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jB6.setForeground(new java.awt.Color(255, 255, 255));
        jB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sellMedicine_64px_32x32.png"))); // NOI18N
        jB6.setText("Sell Medicine");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        jPanel5.add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 250, 40));

        jB7.setBackground(new java.awt.Color(0, 118, 225));
        jB7.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        jB7.setForeground(new java.awt.Color(255, 255, 255));
        jB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_32x32.png"))); // NOI18N
        jB7.setText("Logout");
        jB7.setBorder(null);
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jPanel5.add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 210, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateMedicine().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbActionPerformed
        // TODO add your handling code here:
        String id= Stf.getText();
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from medicine where medId="+id);
            if(rs.next()){
                Tf1.setText(rs.getString(2));
                rsD1.setDatoFecha(rs.getDate(4));
                rsD2.setDatoFecha(rs.getDate(5));
                Tf2.setText(rs.getString(3));
                Tf4.setText(rs.getString(7));
                Tf3.setText(rs.getString(6));
                Tf4.setEditable(false);
            } else{
                JOptionPane.showMessageDialog(null,"Entered Medicine_ID doesn't Exist!");
            }
        } catch(Exception e){
        }
    }//GEN-LAST:event_SbActionPerformed

    private void DbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null,"Do you want to Delete this Medicine data?","Confirm!",JOptionPane.YES_NO_OPTION);
        if(a==0){
            deleteMed();
        }
    }//GEN-LAST:event_DbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] options= {"Dashboard","Exit Application"};
        int a= JOptionPane.showOptionDialog(null,"Your Choice","Select",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,null);
        if(a == 0){
            new Home().setVisible(true);
            dispose();
        } else if(a == 1){
            int b= JOptionPane.showConfirmDialog(null,"Do you really want to exit the Application?","Confirm!",JOptionPane.YES_NO_OPTION);
            if(b == 0){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        new AddMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        new UpdateMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        new ViewMedicine().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        new SellMedicine().setVisible(true);
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        int a= JOptionPane.showConfirmDialog(null,"Do you really want to Logout?","Confirm!",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void UbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbActionPerformed
        // TODO add your handling code here:
        int a= Integer.parseInt(adq.getText());
        int q= Integer.parseInt(Tf4.getText());
        int price= Integer.parseInt(Tf3.getText());
        java.util.Date mfgDate= rsD1.getDatoFecha();
        java.util.Date expDate= rsD2.getDatoFecha();
        Date today= new Date();
        String md= date2str(mfgDate);
        String ed= date2str(expDate);
        String td= date2str(today);
        int m= Integer.parseInt(md);
        int e= Integer.parseInt(ed);
        int t= Integer.parseInt(td);
        int p= a + q;
        try{
            if((a > 100)||(p > 200)){
                JOptionPane.showMessageDialog(null,"Entered Additional quantity exceeds the LIMIT!","Message",JOptionPane.ERROR_MESSAGE);
                adq.setText("");
            }
            else if(price <= 0){
                JOptionPane.showMessageDialog(null,"Price cannot be Negative!","INVALID!",JOptionPane.ERROR_MESSAGE);
                Tf3.setText("");
            }
            else if((mfgDate.compareTo(expDate)>=0)||(m >= t)){
                JOptionPane.showMessageDialog(null,"Please Enter the Valid Date for the 'Manufacture Date'!","INVALID!",JOptionPane.ERROR_MESSAGE);
            }
            else if(((e-m) <= 230)||((e-m) >= 10000)){
                JOptionPane.showMessageDialog(null,"Please Enter the Valid Date for the 'Expiry Date'!","INVALID!",JOptionPane.ERROR_MESSAGE);
            }
            else{
                String qty= Integer.toString(p);
                Tf4.setText(qty);
                adq.setText("");
                updateMed();
            }
        } catch(Exception ex){

        }
    }//GEN-LAST:event_UbActionPerformed

    private void Tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf1ActionPerformed
        // TODO add your handling code here:
        searchMed(Tf1.getText());
    }//GEN-LAST:event_Tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimage;
    private javax.swing.JButton Db;
    private javax.swing.JButton Sb;
    private javax.swing.JTextField Stf;
    private javax.swing.JTextField Tf1;
    private javax.swing.JTextField Tf2;
    private javax.swing.JTextField Tf3;
    private javax.swing.JTextField Tf4;
    private javax.swing.JButton Ub;
    private javax.swing.JTextField adq;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private rojeru_san.componentes.RSDateChooser rsD1;
    private rojeru_san.componentes.RSDateChooser rsD2;
    // End of variables declaration//GEN-END:variables
}
