package Java;


import Project.JConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL H RAJ
 */
public class ValidityPeriod extends javax.swing.JFrame {
    String comm="";

    /**
     * Creates new form ValidityPeriod
     */
    
    DefaultTableModel model;
    public ValidityPeriod() {
        initComponents();
        validt_Table();
        if("".equals(comm)){
            jTA.setForeground(new Color(153,153,153));
            jTA.setText("No Comments...");
        }
        jTA.setEditable(false);
    }
    
    private void validt_Table() {
        try{
            Connection con= JConnection.getCon();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery("select * from medicine");
            while(rs.next()){
                String mId= rs.getString(1);
                String mName= rs.getString(2);
                java.util.Date expDate= rs.getDate(5);
                String period;
                if((period=vldPeriod(mName, expDate)) == null){
                    continue;
                }
                Object[] obj={mId,mName,expDate,period};
                model= (DefaultTableModel)vldtTable.getModel();
                model.addRow(obj);
            }
            jTA.setText(comm);
        } catch(Exception e){}
    }
    
    public String vldPeriod(String name, java.util.Date eDate){
        String ed= date2str(eDate);
        Date today= new Date();
        String td= date2str(today);
        int e= Integer.parseInt(ed);
        int t= Integer.parseInt(td);
        if(e == t){
            comm=comm+name+" has been expired!\n";
        }
        DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyyMMdd");
        LocalDate d1= LocalDate.parse(td,dtf);
        LocalDate d2= LocalDate.parse(ed,dtf);
        long days= ChronoUnit.DAYS.between(d1,d2);
        String p;
        if(days == 0){
            p="EXPIRED Today!";
        }else if(days == 1){
            p="Ends Tomorrow!";
        } else if(days < 0){
            p= null;
        } else if(days < 90){
            p=Long.toString(days)+" days left";
        } else{
            p= null;
        }
        return p;
    }
    
    public String date2str(java.util.Date sdate){
        SimpleDateFormat sdf= new SimpleDateFormat("yyyyMMdd");
        return sdf.format(sdate);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vldtTable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Border = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expmed_1_100x100.png"))); // NOI18N
        jLabel2.setText(" Validity Period");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 430, 90));

        vldtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Med_ID", "Name", "ExpiryDate", "Validity"
            }
        ));
        vldtTable.setColorBackgoundHead(new java.awt.Color(75, 75, 75));
        vldtTable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vldtTable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vldtTable.setColorSelBackgound(new java.awt.Color(51, 51, 51));
        vldtTable.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        vldtTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        vldtTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        vldtTable.setRowHeight(25);
        jScrollPane1.setViewportView(vldtTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 660, 210));

        jTA.setColumns(20);
        jTA.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jTA.setForeground(new java.awt.Color(204, 0, 0));
        jTA.setRows(5);
        jScrollPane2.setViewportView(jTA);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 620, 80));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Comments");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 488, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 530));

        Border.setBackground(new java.awt.Color(51, 51, 51));
        Border.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidityPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidityPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidityPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidityPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidityPeriod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Border;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA;
    private rojeru_san.complementos.RSTableMetro vldtTable;
    // End of variables declaration//GEN-END:variables
}
